"""ajuste coluna

Revision ID: 046ca79d2762
Revises: f154537f4469
Create Date: 2026-01-14 13:17:54.758794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046ca79d2762'
down_revision = 'f154537f4469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
