"""inserido tamanho colunas

Revision ID: 3985c7ee20d5
Revises: 110e505e54e7
Create Date: 2025-12-04 13:41:59.874198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3985c7ee20d5'
down_revision = '110e505e54e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execucao_spsadt', schema=None) as batch_op:
        batch_op.alter_column('indicacao_clinica',
               existing_type=mysql.TINYINT(display_width=1),
               comment='A indicação clinica é descrita pelo médico',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execucao_spsadt', schema=None) as batch_op:
        batch_op.alter_column('indicacao_clinica',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='A indicação clinica é descrita pelo médico',
               existing_nullable=False)

    # ### end Alembic commands ###
