"""fix: primary key column

Revision ID: 78e25b1a5ffc
Revises: 1d304242954e
Create Date: 2026-01-14 15:13:01.020589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e25b1a5ffc'
down_revision = '046ca79d2762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("execucao_spsadt_procedimento")
    op.create_table('execucao_spsadt_procedimento',
    sa.Column('codigo_execucao_procedimento', sa.Integer(), autoincrement=True, nullable=False, comment='Chave primária da tabela.'),
    sa.Column('codigo_procedimento', sa.Integer(), nullable=False, comment='Ver na guia do paciente.'),
    sa.Column('codigo_execucao', sa.Integer(), nullable=False),
    sa.Column('descricao_procedimento', sa.String(length=150), nullable=False, comment='Ver na guia do paciente.'),
    sa.Column('quantidade_solicitada', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['codigo_execucao'], ['execucao_spsadt.codigo_execucao'], ),
    sa.PrimaryKeyConstraint('codigo_execucao_procedimento'),
    sa.UniqueConstraint('codigo_execucao_procedimento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('execucao_spsadt_procedimento')
    # ### end Alembic commands ###
