"""Initial migration.

Revision ID: 7a3f3e600c85
Revises: 
Create Date: 2025-11-22 11:03:06.946686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3f3e600c85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiario',
    sa.Column('numero_carteira', sa.String(length=20), nullable=False),
    sa.Column('atendimento_rn', sa.Boolean(), nullable=False, comment='Define se beneficiário é rem nascido.'),
    sa.Column('nome_beneficiario', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('numero_carteira')
    )
    op.create_table('contratado',
    sa.Column('codigo_prestador_na_operadora', sa.Integer(), nullable=False, comment='O codigo do prestador é definido na operadora.'),
    sa.Column('nome_contratado', sa.String(length=70), nullable=False),
    sa.Column('carater_atendimento', sa.Integer(), nullable=False, comment='1 - Eletiva, 2 - Urgência/Emergencia'),
    sa.Column('tipo_atendimento', sa.Integer(), nullable=False, comment='Ver tiss/schemas.'),
    sa.PrimaryKeyConstraint('codigo_prestador_na_operadora'),
    sa.UniqueConstraint('codigo_prestador_na_operadora')
    )
    op.create_table('operadora',
    sa.Column('registro_ans', sa.Integer(), nullable=False, comment='Nº de registro da operadora na ANS.'),
    sa.Column('operadora', sa.String(length=30), nullable=False, comment='Nome da operadora'),
    sa.PrimaryKeyConstraint('registro_ans'),
    sa.UniqueConstraint('registro_ans')
    )
    op.create_table('solicitante',
    sa.Column('codigo_solicitante', sa.Integer(), nullable=False),
    sa.Column('profissional_solicitante', sa.String(length=70), nullable=False),
    sa.Column('conselho_profissional', sa.Integer(), nullable=False),
    sa.Column('numero_conselho_profissional', sa.String(length=15), nullable=False),
    sa.Column('uf', sa.Integer(), nullable=False),
    sa.Column('cbos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('codigo_solicitante'),
    sa.UniqueConstraint('codigo_solicitante')
    )
    op.create_table('tipo_user',
    sa.Column('cod_tipo_user', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cod_tipo_user'),
    sa.UniqueConstraint('cod_tipo_user')
    )
    op.create_table('users',
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('senha', sa.String(length=30), nullable=False),
    sa.Column('tipo_usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_usuario_id'], ['tipo_user.cod_tipo_user'], ),
    sa.PrimaryKeyConstraint('login'),
    sa.UniqueConstraint('login')
    )
    op.create_table('execucao_spsadt',
    sa.Column('codigo_execucao', sa.Integer(), nullable=False),
    sa.Column('codigo_beneficiario', sa.String(length=20), nullable=False),
    sa.Column('codigo_contratado', sa.Integer(), nullable=False),
    sa.Column('codigo_solicitante', sa.Integer(), nullable=False),
    sa.Column('operadora_registro_ans', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('indicacao_clinica', sa.Boolean(), nullable=False),
    sa.Column('indicacao_acidente', sa.Integer(), nullable=False, comment='Ver tiss/schema.'),
    sa.Column('observacao', sa.Text(length=500), nullable=False),
    sa.Column('senha', sa.String(length=20), nullable=False),
    sa.Column('tipo_transacao', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['codigo_beneficiario'], ['beneficiario.numero_carteira'], ),
    sa.ForeignKeyConstraint(['codigo_contratado'], ['contratado.codigo_prestador_na_operadora'], ),
    sa.ForeignKeyConstraint(['codigo_solicitante'], ['solicitante.codigo_solicitante'], ),
    sa.ForeignKeyConstraint(['login'], ['users.login'], ),
    sa.ForeignKeyConstraint(['operadora_registro_ans'], ['operadora.registro_ans'], ),
    sa.PrimaryKeyConstraint('codigo_execucao'),
    sa.UniqueConstraint('codigo_execucao')
    )
    op.create_table('execucao_spsadt_procedimento',
    sa.Column('codigo_procedimento', sa.Integer(), nullable=False, comment='Ver na guia do paciente.'),
    sa.Column('codigo_execucao', sa.Integer(), nullable=False),
    sa.Column('descricao_procedimento', sa.String(length=150), nullable=False, comment='Ver na guia do paciente.'),
    sa.Column('quantidade_solicitada', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['codigo_execucao'], ['execucao_spsadt.codigo_execucao'], ),
    sa.PrimaryKeyConstraint('codigo_procedimento')
    )
    op.create_table('transacao',
    sa.Column('sequencia_transacao', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_execucao_sp_sadt', sa.Integer(), nullable=False),
    sa.Column('data_registro_transacao', sa.Date(), nullable=True),
    sa.Column('hora_registro_transacao', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_execucao_sp_sadt'], ['execucao_spsadt.codigo_execucao'], ),
    sa.PrimaryKeyConstraint('sequencia_transacao'),
    sa.UniqueConstraint('sequencia_transacao')
    )
    op.create_table('transacao_status',
    sa.Column('codigo_transacao_status', sa.Integer(), nullable=False),
    sa.Column('codigo_transacao', sa.Integer(), nullable=False),
    sa.Column('codigo_status', sa.Integer(), nullable=False, comment='Ver tiss/schema.'),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_transacao'], ['transacao.sequencia_transacao'], ),
    sa.PrimaryKeyConstraint('codigo_transacao_status'),
    sa.UniqueConstraint('codigo_transacao_status')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacao_status')
    op.drop_table('transacao')
    op.drop_table('execucao_spsadt_procedimento')
    op.drop_table('execucao_spsadt')
    op.drop_table('users')
    op.drop_table('tipo_user')
    op.drop_table('solicitante')
    op.drop_table('operadora')
    op.drop_table('contratado')
    op.drop_table('beneficiario')
    # ### end Alembic commands ###
