"""adicionado enum na coluna carater_atendimento tabela contratado

Revision ID: acf96eaffcbb
Revises: cd7f481ccb14
Create Date: 2025-12-12 13:01:38.457631

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "acf96eaffcbb"
down_revision = "cd7f481ccb14"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contratado", schema=None) as batch_op:
        batch_op.alter_column(
            "carater_atendimento",
            existing_type=sa.INTEGER(),
            type_=sa.Enum("1", "2"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contratado", schema=None) as batch_op:
        batch_op.alter_column(
            "carater_atendimento",
            existing_type=sa.Enum("1", "2"),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
