"""retirado chave rpimária da coluna codigo_procedimento, adicionado coluna codigo_execucao_procedimento

Revision ID: cd7f481ccb14
Revises: 3985c7ee20d5
Create Date: 2025-12-09 11:19:42.938075

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cd7f481ccb14"
down_revision = "3985c7ee20d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("execucao_spsadt_procedimento", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "codigo_execucao_procedimento",
                sa.Integer(),
                nullable=False,
                comment="Chave primária da tabela.",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("execucao_spsadt_procedimento", schema=None) as batch_op:
        batch_op.drop_column("codigo_execucao_procedimento")

    # ### end Alembic commands ###
