"""adicionado enum(1,2...22) na coluna carater_atendimento tabela contratado

Revision ID: f154537f4469
Revises: acf96eaffcbb
Create Date: 2025-12-13 14:27:23.285302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f154537f4469'
down_revision = 'acf96eaffcbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contratado', schema=None) as batch_op:
        batch_op.alter_column('tipo_atendimento',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', name='tipo_atendimento_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contratado', schema=None) as batch_op:
        batch_op.alter_column('tipo_atendimento',
               existing_type=sa.Enum('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', name='tipo_atendimento_enum'),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
